// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqrwgmzgpqafwjptbfgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxcndnbXpncHFhZndqcHRiZmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjU1MjYsImV4cCI6MjA2MTY0MTUyNn0.oXmo8jgHIHvXXrw7XF2On3WtsNfC0lFEARqvXMLvl-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);